[project]
name = "helical-workbench-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi[standard]>=0.129.2",
]

[tool.setuptools.packages.find]
where = ["src"]
